### ISSUE TITLE
a problem with dependency on solidus frontend

### ISSUE THREAD

**Issue by bosskovic** [solidusio/solidus_signifyd#24]
Hi,

in the gemspec there is a dependency on solidus, and solidus includes backend, frontend, core and api.
This is a problem when you do not want frontend gem added.

Would it be possible to replace the dependency on solidus with one on core only, something like here:

https://github.com/Xpitality/solidus_signifyd/blob/master/solidus_signifyd.gemspec#L24

Or if you know of any way of not having frontend included from solidus, that would be great too.

Thanks!

**Comment by Senjai** [comment]
Yes, in the gemspec we should probably kill the solidus dependency in favor of just core, backend and api. This is on our list already for one of our projects, but if you felt like submitting a pull request we'd be happy to consider it.

**Comment by Senjai** [comment]
I just realized you had a PR already for this. Could you rebase it perhaps?

**Comment by bosskovic** [comment]
sure, here it is

**Comment by Senjai** [comment]
Thanks
